<?php

    $tsource = "";

    $r = new ReflectionObject($this);
    if ($r->hasProperty("resultado") && !empty($this->resultado) ) {
        $tsource = $this->resultado;
    }
?>

<script type="text/Javascript">
    
function getDelete(item) { 
    return "<button onclick=\"location.href='/report?command=delete&reportNo=" + jsonStore.getIdentity(item) + "'\">Delete</button>";
}

function gotoeq(value, rowIndex)
{
    return "<a href='/client/service/view/idequipment/"+value+"'> ver serviços " + value + " </a>";
}

    <?php
    if (!empty($tsource)) {
    ?>
        var tSource = <?= $this->resultado; ?>;
    <?php
    }
    ?>
    function escolherEq(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "idequipment");
    	location.href = "/client/equipment/v/id/" + selected_id;
    }
        
    var gotItemsEq = function(items, request){
        console.log("Number of items located: " + items.length);
        dojo.byId("the_total").innerHTML = "Total: " + items.length;
    };
    
    var jsonStore = new dojo.data.ItemFileReadStore({
        <?php 
        if (empty($tsource)) { ?>
            url: '/client/equipment/getajax/idclient/<?= $this->idclient ?>'
        <?php
        } else {
        ?>
            data: tSource
        <?php
        }
        ?>,
        id: 'jsonStore'
    });
    
    jsonStore.fetch({onComplete: gotItemsEq});
    
</script>

<table dojoType="dojox.grid.EnhancedGrid" id="gridNode" jsid="grid" 
       query="{ idequipment: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true"
       style="width: 100%; height: 400px" onRowDblClick='escolherEq();'
       plugins="{
        exporter: true
        }"
>
<thead>
<tr>
    <th field="idequipment" formatter="gotoeq" width="100">ID</th>
    <th field="type" width="100">Tipo</th>
    <th field="name" width="140">Nome</th>
    <th field="datain" width="140">Data colocado</th>
    <th field="dataout" width="140">Data removido</th>
    <th field="serialnum" width="140">S/N</th>
    <th field="macaddr" width="140">MAC</th>
    <th field="full_model_description" width="140">Modelo</th>
</tr>
</thead>
</table>
<div style="float: left;">
<span id="the_total">Total: </span>
<button data-dojo-type="dijit.form.Button" type="button">CSV
    <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
        grid.exportGrid("csv", {writerArgs: {separator:";"}}, function(str) {
            // do something interesting with str
            
            var form = document.createElement('form');
            dojo.attr(form, 'method', 'POST');
            document.body.appendChild(form);
            
            dojo.io.iframe.send({
                    url: "/docsismodem/exporttocsv/",
                    form: form,
                    method: "POST",
                    content: {exp: str},
                    timeout: 1500
            });
            document.body.removeChild(form);
        });
    </script>
</button>
</div>

<div style="float: left;">
<button data-dojo-type="dijit.form.Button" type="button">Novo
    <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
        location.href = "/client/equipment/new/idclient/<?= $this->idclient ?>";
    </script>
</button>
</div>