<?php

/**
 * This file belongs to the Docsis Manager for managing ISC dhcp and 
 * docsis server table (docsismodem) for a cable network it provides some
 * utilization and information gathering tools for easy management of the cable
 * modem network and provision of CPE and other ISP related equipments.
 * 
 * Copyright (C) 2011  Fernando André <netriver at gmail dot com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 */

if ($this->type === null || $this->type == 'model') {
    $tmp    = 'getmodels';
    $id     = 'idmodel';
    $arr    = array('idmodel' => "Id", 'description' => 'Nome', 'vendormac' => "Vendor", 'name' => "Marca");
} else {
    $tmp    = 'getbrands';
    $id     = 'idbrand';
    $arr    = array('idbrand' => "Id", 'name' => 'Nome');
}

?>
<script type="text/Javascript">

    /*
     * Choose the device row to view
     */
    function escolher(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "<?php print $id ?>");
    	location.href = "/device/v/?id="+selected_id+"&type=<?php print $tmp ?>";
    }
</script>
<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" url="/device/<?php print $tmp ?>" id="store" />
<table dojoType="dojox.grid.DataGrid" id="gridNode" jsid="grid" query="{ <?php echo $id ?>: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true"
       style="width: 400px; height: 200px" onRowDblClick='escolher();'>
<thead>
<tr>
    <?php 
    foreach ($arr as $ke => $val ) {
    ?>
    <th field="<?php print $ke ?>" width="100px" ><?php print $val ?></th>
    <?php
    }
    ?>
</tr>
</thead>
</table>
