<script type="text/Javascript">


/**
 * This file belongs to the Docsis Manager for managing ISC dhcp and 
 * docsis server table (docsismodem) for a cable network it provides some
 * utilization and information gathering tools for easy management of the cable
 * modem network and provision of CPE and other ISP related equipments.
 * 
 * Copyright (C) 2011  Fernando André <netriver at gmail dot com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 */

    function escolher(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "<?php print $this->idfield ?>");
    	location.href = "/users/<?php print $this->controller ?>/v/id/"+selected_id;
    }    
</script>
<?php
if ($this->estado === null || $this->estado == 'activos') {
    $tmp = '';
    if (trim($this->resultado) != '') {

    }
} else {
    $tmp = '?estado=inactivos';
}

$obj = new ReflectionObject($this);

if ( $obj->hasProperty("resultado") && !empty($this->resultado)) {
?>
<script type='text/Javascript'>    
 jsonData = <?php print $this->resultado ?>;
</script>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" data="jsonData" id="store" />
<?php
} else {
?>
<button data-dojo-type="dijit.form.Button" type="button" id="go">Novo
  <script type="dojo/connect" data-dojo-event="onClick">
    window.location = '/users/<?php print $this->controller ?>/v';
  </script>
</button>
<a href="javascript: search();">Procurar</a>
<div id="docsisform" style="width: 50%;">
<?php
    print $this->procura;
?>
    
    <span style="float: right;">
        <a href="javascript:hidesearch();">Esconder formul&aacute;rio</a>
    </span>
    <br/>
</div>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" 
     url="/users/<?php print $this->controller ?>/getajax<?php print $tmp ?>" id="store" />
<?php
}
?>
<table dojoType="dojox.grid.DataGrid" id="gridNode" jsid="grid" 
       query="{ <?php print $this->idfield ?>: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true" onRowDblClick='escolher();'
       style="width: 100%; height: 400px">
<thead>
<tr>
    <?php
    foreach($this->columns as $name => $label ) {
    ?>
    <th field="<?php print $name ?>" ><?php print $label ?></th>
    <?php
    }
    ?>
</tr>
</thead>
</table>
<script type="text/javascript">
    
    hidesearch();
    
    function search()
    {
        dojo.style('docsisform', { 'display' : 'block' });
    }
    
    function hidesearch()
    {
        dojo.style('docsisform', { 'display' : 'none' });
    }
    
</script>