<?php

/**
 * This file belongs to the Docsis Manager for managing ISC dhcp and
 * docsis server table (docsismodem) for a cable network it provides some
 * utilization and information gathering tools for easy management of the cable
 * modem network and provision of CPE and other ISP related equipments.
 *
 * Copyright (C) 2011  Fernando André <netriver at gmail dot com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */
    $tsource = "";

    $r = new ReflectionObject($this);
    if ($r->hasProperty("resultado") && !empty($this->resultado) ) {
        $tsource = $this->resultado;
    }
?>

<script type="text/Javascript">
    <?php
    if (!empty($tsource)) {
    ?>
        var tSource = <?= $this->resultado; ?>;
    <?php
    }
    ?>
    function escolher(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "macaddr");
    	location.href = "/docsismodem/ver/id/"+selected_id;
    }

    var gotItems = function(items, request){
        console.log("Number of items located: " + items.length);
        dojo.byId("the_total").innerHTML = "Total: " + items.length;
    };

    var jsonStore = new dojo.data.ItemFileReadStore({
        <?php
        if (empty($tsource)) { ?>
            url: '/docsissignal/getajax/'
        <?php
        } else {
        ?>
            data: tSource
        <?php
        }
        ?>,
        id: 'jsonStore'
    });

    jsonStore.fetch({onComplete: gotItems});

</script>

<table dojoType="dojox.grid.EnhancedGrid" id="gridNode" jsid="grid"
       query="{ macaddr: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true"
       style="width: 100%; height: 400px" onRowDblClick='escolher();'
       plugins="{
        exporter: true
        }"
>
<thead>
<tr>
    <th field="idtx">ID</th>
    <th field="macaddr" width="100">Mac Address</th>
    <th field="node" >Celula</th>
    <th field="tx" formatter="validarTX" width="140">TX</th>
    <th field="snr" formatter="validarSNR" width="140">SNR</th>
    <th field="rx" formatter="validarRX" >RX</th>
    <th field="microreflections">Micro-Reflections</th>
    <th field="dschannelid" >DS_ID</th>
    <th field="uschannelid" >US_ID</th>
    <th field="lastip" >Last IP</th>
    <th field="data" width="140px">Data</th>
</tr>
</thead>
</table>
<span id="the_total">Total: </span>
<button data-dojo-type="dijit.form.Button" type="button">CSV
    <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
        grid.exportGrid("csv", {writerArgs: {separator:";"}}, function(str) {
            // do something interesting with str

            var form = document.createElement('form');
            dojo.attr(form, 'method', 'POST');
            document.body.appendChild(form);

            dojo.io.iframe.send({
                    url: "/docsismodem/exporttocsv/",
                    form: form,
                    method: "POST",
                    content: {exp: str},
                    timeout: 1500
            });
            document.body.removeChild(form);
        });
    </script>
</button>