<script type="text/Javascript">
    
/**
 * This file belongs to the Docsis Manager for managing ISC dhcp and 
 * docsis server table (docsismodem) for a cable network it provides some
 * utilization and information gathering tools for easy management of the cable
 * modem network and provision of CPE and other ISP related equipments.
 * 
 * Copyright (C) 2011  Fernando André <netriver at gmail dot com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 */

    function escolher(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "idprivilege");
    	location.href = "/users/privilege/v/id/"+selected_id;
    }    
</script>
<?php
if ($this->estado === null || $this->estado == 'activos') {
    $tmp = '';
    if (trim($this->resultado) != '') {

    }
} else {
    $tmp = '?estado=inactivos';
}

$obj = new ReflectionObject($this);

if ( $obj->hasProperty("resultado") && !empty($this->resultado)) {
?>
<script type='text/Javascript'>
 jsonData = <?php print $this->resultado ?>;
</script>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" data="jsonData" id="store" />
<?php
} else {
?>

<a href="javascript: search();">Procurar</a>
<div id="docsisform" style="width: 50%;">
<?php
    print $this->procura;
?>
    
    <span style="float: right;">
        <a href="javascript:hidesearch();">Esconder formul&aacute;rio</a>
    </span>
    <br/>
</div>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" 
     url="/users/privilege/getajax<?php print $tmp ?>" id="store" />
<?php
}
?>
<table dojoType="dojox.grid.DataGrid" id="gridNode" jsid="grid" 
       query="{ <?php print $idfield ?>: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true"
       style="width: 100%; height: 400px" onRowClick='escolher();'>
<thead>
<tr>
    <th field="idprivilege" >ID</th>
    <th field="modulename" >Modulo</th>
    <th field="controllername" >Pagina</th>
    <th field="controlleraction" >Acção</th>
    <th field="group" >Grupo</th>
    <th field="r" >Ler</th>
    <th field="w" >Editar</th>
    <th field="d" >Apagar</th>
</tr>
</thead>
</table>

<script type="text/javascript">
    
    hidesearchCM();
    
    function search()
    {
        dojo.style('docsisform', { 'display' : 'block' });
    }
    
    function hidesearch()
    {
        dojo.style('docsisform', { 'display' : 'none' });
    }
    
</script>