<script type="text/Javascript">
    function escolher(event)
    {
    	selected_index = grid.focus.rowIndex;
    	selected_item = grid.getItem(selected_index);
    	//Not sure if this is the most efficient way but it worked for me
    	selected_id = grid.store.getValue(selected_item, "idclient");
    	location.href = "/client/client/new/id/"+selected_id;
    }    
</script>
<?php
if ($this->estado === null || $this->estado == 'activos') {
    $tmp = '';
    if (trim($this->resultado) != '') {

    }
} else {
    $tmp = '?estado=inactivos';
}

$obj = new ReflectionObject($this);

if ( $obj->hasProperty("resultado") && !empty($this->resultado)) {
?>
<script type='text/Javascript'>
 jsonData = <?php print $this->resultado ?>;
</script>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" data="jsonData" id="store" />
<?php
} else {
?>

<div dojoType="dojo.data.ItemFileReadStore" jsId="jsonStore" 
     url="/client/client/getajax<?php print $tmp ?>" id="store" />
<?php
}
?>
<table dojoType="dojox.grid.DataGrid" id="gridNode" jsid="grid" 
       query="{ idclient: '*' }" store="jsonStore"
       selectionMode="single" autoWidth="true"
       style="width: 100%; height: 400px" onRowDblClick='escolher();'>
<thead>
<tr>
    <th field="idclient" width="40">#ID</th>
    <th field="name" width="200">Nome</th>
    <th field="contract">Contrato</th>
    <th field="node">Celula</th>
    <th field="state">Estado</th>
    <th field="datain" width="120X">Data/Inserido</th>
</tr>
</thead>
</table>